version: '{build}'
os: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_tags: true
before_build:
  - ps: >-
      nuget restore
build:
  verbosity: minimal
  publish_nuget: true
  include_nuget_references: true
after_build:
  - ps: >-
      $artifacts = "Binaries\Yuzu"

      New-Item -Type directory $artifacts

      Get-ChildItem Yuzu\bin\$env:CONFIGURATION | Copy-Item -Destination $artifacts -Recurse -Container

      Get-ChildItem $artifacts -File -Recurse -Exclude *.exe, *.dll, *.config, *.mp3 | Remove-Item

      $shell = New-Object -ComObject("WScript.Shell")

      $wiki = $shell.CreateShortcut("$env:APPVEYOR_BUILD_FOLDER\$artifacts\Yuzu Wiki.url")

      $wiki.TargetPath = "https://github.com/paralleltree/Yuzu/wiki"

      $wiki.Save()
artifacts:
  - path: Binaries
    name: Yuzu
deploy:
  - provider: GitHub
    release: Yuzu
    auth_token:
      secure: skcRxFXBYneRSuIzbQmeYLKFu8aaGAfL7VB5vE9lYd8ZCw3HgDms/3N6lvL6GqKR
    artifact: Yuzu
    draft: true
    on:
      branch: master
  - provider: NuGet
    api_key:
      secure: 2+qwVmcWw50e4IHnQlT7xCHcUFg29AzhID0ztoBgLtduZfcTyw8UEAauj/GL43vn
    skip_symbols: false
    on:
      branch: master
cache:
  - packages -> **\packages.config
